pipeline {
   environment {
        dockerImage = '' 
    }
   agent any
   stages {
      stage('images') {
          steps {
              script { 
                    dockerImage = docker.build registry + ":$BUILD_NUMBER" 
                }
          }
     }
   }
}
