pipeline {
    agent { 
        label 'staging' 
    }
    stages {
        stage('creat docker') {
            steps {
                echo '------------- start building -------------'
                sh 'docker build ../'
            }
        }
    }
}
