pipeline {
   agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
   stages {
      stage ('Test') {
        steps {
           sh 'docker -v'
          sh 'node -v'
          sh 'npm -v'
        }
      }
   }
}
